CREATE DATABASE seebee collate sql_latin1_general_cp1_cs_as;

ALTER DATABASE seebee
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON)

go

ALTER DATABASE seebee
SET ALLOW_SNAPSHOT_ISOLATION ON

go

USE seebee;


CREATE TABLE USERS(
    id INTEGER IDENTITY NOT NULL,
    name varchar(32) UNIQUE NOT NULL,
    age INTEGER NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE USERS
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)

CREATE TABLE SWITCHES(
    id INTEGER NOT NULL,
    name varchar(32) UNIQUE NOT NULL,
    state INTEGER NOT NULL,
    CONSTRAINT pk_switches PRIMARY KEY (id)
);

ALTER TABLE SWITCHES
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)


go
