language: java

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer
      
dist: trusty
sudo: false
      
notifications:
  email:
    recipients:
      - minborg@speedment.com
      - dan@speedment.com
    on_success: never  # default: change
    on_failure: always # default: always

