#
#
# Copyright (c) 2017-2018, Namely, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); You may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

version: '2'
services:
  sqlserver:
    build: tests/sql-server-test/src/test/resources/sqlserver
    ports:
     - "1433:1433"
  seebee:
    build:
      context: ${SEE_BEE_APP_PATH}
      args:
        JAR_FILE: ${SEE_BEE_JAR}
    volumes:
     - /tmp/parquet:/parquet
    links:
     - sqlserver
    depends_on:
      - sqlserver
    command: --system.loggingLevel=FINE
  sparks:
    build: tests/sql-server-test/src/test/resources/spark
    volumes:
     - /tmp/parquet/spool:/spool
    command: spark-submit /stream_table.py SWITCHES
    depends_on:
      - seebee
