version: '2'
services:

  sqlserver:
    build: sqlserver
    image: pt_sqlserver

  seebee:
    build:
      context: ../../applications/sql-server-parquet-application
      args:
        JAR_FILE: sql-server-parquet-application-0.0.2-SNAPSHOT-jar-with-dependencies.jar
    image: pt_seebee
    container_name: ${SEEBEE_CONTAINER_NAME}
    volumes:
      - data:/parquet
    links:
      - sqlserver
    depends_on:
      - sqlserver
    command: ${SEEBEE_PARAMS}

  tester:
    build: tester
    image: pt_tester
    container_name: ${TESTER_CONTAINER_NAME}
    links:
      - sqlserver
    volumes:
      - data:/parquet:ro
    depends_on:
      - seebee

volumes:
  data:
